using SpaceDebrisMonitor.Domain.Enums;

namespace SpaceDebrisMonitor.Domain.Entities;

/// <summary>
/// Represents a collision risk alert generated by the monitoring system.
/// Links a debris object to the satellite at risk.
/// </summary>
public class Alert : BaseEntity
{
    public AlertSeverity Severity { get; private set; }
    public AlertStatus Status { get; private set; }
    public string Title { get; private set; } = string.Empty;
    public string Message { get; private set; } = string.Empty;
    public double EstimatedDistanceKm { get; private set; }
    public double CollisionProbability { get; private set; }
    public DateTime? PredictedClosestApproach { get; private set; }
    public DateTime? AcknowledgedAt { get; private set; }
    public DateTime? ResolvedAt { get; private set; }
    public string? ResolutionNotes { get; private set; }

    public Guid SpaceDebrisId { get; private set; }
    public SpaceDebris SpaceDebris { get; private set; } = null!;

    public Guid? SatelliteId { get; private set; }
    public Satellite? Satellite { get; private set; }

    protected Alert() { }

    public Alert(
        Guid spaceDebrisId,
        AlertSeverity severity,
        string title,
        string message,
        double estimatedDistanceKm,
        double collisionProbability,
        Guid? satelliteId = null,
        DateTime? predictedClosestApproach = null)
    {
        if (string.IsNullOrWhiteSpace(title)) throw new ArgumentException("Título é obrigatório.");
        if (string.IsNullOrWhiteSpace(message)) throw new ArgumentException("Mensagem é obrigatória.");
        if (estimatedDistanceKm < 0) throw new ArgumentOutOfRangeException(nameof(estimatedDistanceKm));
        if (collisionProbability < 0 || collisionProbability > 1) throw new ArgumentOutOfRangeException(nameof(collisionProbability));

        SpaceDebrisId = spaceDebrisId;
        SatelliteId = satelliteId;
        Severity = severity;
        Status = AlertStatus.Active;
        Title = title;
        Message = message;
        EstimatedDistanceKm = estimatedDistanceKm;
        CollisionProbability = collisionProbability;
        PredictedClosestApproach = predictedClosestApproach;
    }

    public static AlertSeverity DetermineSeverity(double distanceKm, double probability) =>
        (distanceKm, probability) switch
        {
            ( < 1, > 0.05) => AlertSeverity.Critical,
            ( < 5, > 0.01) => AlertSeverity.High,
            ( < 25, > 0.001) => AlertSeverity.Medium,
            _ => AlertSeverity.Low
        };

    public void Acknowledge()
    {
        if (Status != AlertStatus.Active)
            throw new InvalidOperationException("Somente alertas ativos podem ser reconhecidos.");
        Status = AlertStatus.Acknowledged;
        AcknowledgedAt = DateTime.UtcNow;
        MarkAsUpdated();
    }

    public void Resolve(string notes)
    {
        if (Status == AlertStatus.Resolved)
            throw new InvalidOperationException("O alerta já está resolvido.");
        Status = AlertStatus.Resolved;
        ResolvedAt = DateTime.UtcNow;
        ResolutionNotes = notes;
        MarkAsUpdated();
    }

    public void MarkAsFalsePositive(string reason)
    {
        Status = AlertStatus.FalsePositive;
        ResolutionNotes = reason;
        ResolvedAt = DateTime.UtcNow;
        MarkAsUpdated();
    }

    public TimeSpan? TimeUntilApproach() =>
        PredictedClosestApproach.HasValue
            ? PredictedClosestApproach.Value - DateTime.UtcNow
            : null;
}
